import type { ComponentType } from "react"
import type { ToolboxToolId } from "./types"

type ToolModule = { default: ComponentType }

export const TOOL_LOADERS: Record<ToolboxToolId, () => Promise<ToolModule>> = {
  "text-stats": () => import("./tools/text/text-stats"),
  "text-clean": () => import("./tools/text/text-clean"),
  "line-dedupe-sort": () => import("./tools/text/line-dedupe-sort"),
  "case-naming": () => import("./tools/text/case-naming"),
  "text-diff": () => import("./tools/text/text-diff"),
  "find-replace": () => import("./tools/text/find-replace"),
  "markdown-preview": () => import("./tools/text/markdown-preview"),
  "zh-convert": () => import("./tools/text/zh-convert"),
  "json-format": () => import("./tools/dev/json-format"),
  timestamp: () => import("./tools/dev/timestamp"),
  uuid: () => import("./tools/dev/uuid"),
  "json-yaml": () => import("./tools/dev/json-yaml"),
  "json-csv": () => import("./tools/dev/json-csv"),
  "regex-tester": () => import("./tools/dev/regex-tester"),
  cron: () => import("./tools/dev/cron"),
  "sql-format": () => import("./tools/dev/sql-format"),
  "code-format": () => import("./tools/dev/code-format"),
  base64: () => import("./tools/encoding/base64"),
  "url-codec": () => import("./tools/encoding/url-codec"),
  "hex-string": () => import("./tools/encoding/hex-string"),
  "html-entities": () => import("./tools/encoding/html-entities"),
  "unicode-escape": () => import("./tools/encoding/unicode-escape"),
  radix: () => import("./tools/encoding/radix"),
  "symmetric-cipher": () => import("./tools/crypto/symmetric-cipher"),
  hash: () => import("./tools/crypto/hash"),
  hmac: () => import("./tools/crypto/hmac"),
  "password-gen": () => import("./tools/crypto/password-gen"),
  "asymmetric-cipher": () => import("./tools/crypto/asymmetric-cipher"),
  jwt: () => import("./tools/crypto/jwt"),
  "password-strength": () => import("./tools/crypto/password-strength"),
  totp: () => import("./tools/crypto/totp"),
  bcrypt: () => import("./tools/crypto/bcrypt"),
  "cert-pem": () => import("./tools/crypto/cert-pem"),
  "image-compress": () => import("./tools/image/image-compress"),
  "color-convert": () => import("./tools/image/color-convert"),
  "image-crop": () => import("./tools/image/image-crop"),
  "image-watermark": () => import("./tools/image/image-watermark"),
  "image-stitch": () => import("./tools/image/image-stitch"),
  "qr-generate": () => import("./tools/general/qr-generate"),
  "qr-decode": () => import("./tools/general/qr-decode"),
  "unit-convert": () => import("./tools/general/unit-convert"),
  "date-diff": () => import("./tools/general/date-diff"),
}
