//! 建立个人 Wiki 最初的来源、任务、项目绑定、贡献和资料库表。
//! 这是已发布迁移历史；后续 v2 迁移会清理旧数据和弃用表，不能按当前模型直接删去本迁移。

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(WikiVault::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(WikiVault::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(WikiVault::CanonicalPath).text().not_null())
                    .col(
                        ColumnDef::new(WikiVault::ConfigRevision)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(WikiVault::NextCompileAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WikiVault::IsActive)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(WikiVault::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiVault::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_wiki_vault_canonical_path")
                    .table(WikiVault::Table)
                    .col(WikiVault::CanonicalPath)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(WikiProjectBinding::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(WikiProjectBinding::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(WikiProjectBinding::VaultId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiProjectBinding::DbInstanceId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiProjectBinding::RootFolderId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiProjectBinding::ProjectNoteId)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WikiProjectBinding::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiProjectBinding::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_wiki_project_binding_unique")
                    .table(WikiProjectBinding::Table)
                    .col(WikiProjectBinding::VaultId)
                    .col(WikiProjectBinding::DbInstanceId)
                    .col(WikiProjectBinding::RootFolderId)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(WikiSource::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(WikiSource::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(WikiSource::SourceGroupId)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(WikiSource::VaultId).string().not_null())
                    .col(ColumnDef::new(WikiSource::SourceKind).string().not_null())
                    .col(
                        ColumnDef::new(WikiSource::SourceSeq)
                            .big_integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(WikiSource::RunId).string().null())
                    .col(ColumnDef::new(WikiSource::OriginalHash).string().null())
                    .col(ColumnDef::new(WikiSource::RawPath).text().null())
                    .col(ColumnDef::new(WikiSource::RawHash).string().null())
                    .col(ColumnDef::new(WikiSource::ExtractorVersion).string().null())
                    .col(ColumnDef::new(WikiSource::CoverageStatus).string().null())
                    .col(
                        ColumnDef::new(WikiSource::Eligibility)
                            .string()
                            .not_null()
                            .default("processing"),
                    )
                    .col(ColumnDef::new(WikiSource::MaterialRole).string().null())
                    .col(ColumnDef::new(WikiSource::PersonalRole).text().null())
                    .col(
                        ColumnDef::new(WikiSource::AnnotationRevision)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(WikiSource::ConversationId).integer().null())
                    .col(ColumnDef::new(WikiSource::FolderId).integer().null())
                    .col(ColumnDef::new(WikiSource::RootFolderId).integer().null())
                    .col(ColumnDef::new(WikiSource::AgentType).string().null())
                    .col(ColumnDef::new(WikiSource::Model).string().null())
                    .col(ColumnDef::new(WikiSource::Mode).string().null())
                    .col(
                        ColumnDef::new(WikiSource::CapturedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WikiSource::OccurredAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WikiSource::Truncated)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(WikiSource::Redacted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(WikiSource::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiSource::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .get_connection()
            .execute_unprepared(
                "CREATE UNIQUE INDEX IF NOT EXISTS idx_wiki_source_vault_run \
                 ON wiki_source (vault_id, run_id) WHERE run_id IS NOT NULL",
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_wiki_source_vault_seq")
                    .table(WikiSource::Table)
                    .col(WikiSource::VaultId)
                    .col(WikiSource::SourceSeq)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(WikiJob::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(WikiJob::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(WikiJob::VaultId).string().not_null())
                    .col(ColumnDef::new(WikiJob::SourceId).string().null())
                    .col(ColumnDef::new(WikiJob::Kind).string().not_null())
                    .col(ColumnDef::new(WikiJob::Status).string().not_null())
                    .col(ColumnDef::new(WikiJob::DedupeKey).string().null())
                    .col(ColumnDef::new(WikiJob::InputManifest).text().null())
                    .col(ColumnDef::new(WikiJob::ConfigVersion).string().null())
                    .col(ColumnDef::new(WikiJob::ModelId).string().null())
                    .col(ColumnDef::new(WikiJob::Protocol).string().null())
                    .col(
                        ColumnDef::new(WikiJob::Attempt)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .col(ColumnDef::new(WikiJob::ErrorCode).string().null())
                    .col(ColumnDef::new(WikiJob::ErrorMessage).text().null())
                    .col(ColumnDef::new(WikiJob::OutputManifest).text().null())
                    .col(
                        ColumnDef::new(WikiJob::StartedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WikiJob::FinishedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WikiJob::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiJob::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_wiki_job_vault_status")
                    .table(WikiJob::Table)
                    .col(WikiJob::VaultId)
                    .col(WikiJob::Status)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_wiki_job_source")
                    .table(WikiJob::Table)
                    .col(WikiJob::SourceId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(WikiSourceSegment::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(WikiSourceSegment::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(WikiSourceSegment::SourceId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiSourceSegment::SegmentId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiSourceSegment::ContentHash)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(WikiSourceSegment::Locator).text().null())
                    .col(
                        ColumnDef::new(WikiSourceSegment::AnnotationRevision)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(WikiSourceSegment::CompileContractVersion)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WikiSourceSegment::AnalysisConfigVersion)
                            .string()
                            .null(),
                    )
                    .col(ColumnDef::new(WikiSourceSegment::Stage).string().null())
                    .col(ColumnDef::new(WikiSourceSegment::Artifact).text().null())
                    .col(
                        ColumnDef::new(WikiSourceSegment::Status)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiSourceSegment::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiSourceSegment::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_wiki_source_segment_unique")
                    .table(WikiSourceSegment::Table)
                    .col(WikiSourceSegment::SourceId)
                    .col(WikiSourceSegment::SegmentId)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(WikiCompileInput::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(WikiCompileInput::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(WikiCompileInput::SourceId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiCompileInput::RawHash)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiCompileInput::AnnotationRevision)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiCompileInput::CompileContractVersion)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiCompileInput::CommittedJobId)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WikiCompileInput::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_wiki_compile_input_unique")
                    .table(WikiCompileInput::Table)
                    .col(WikiCompileInput::SourceId)
                    .col(WikiCompileInput::RawHash)
                    .col(WikiCompileInput::AnnotationRevision)
                    .col(WikiCompileInput::CompileContractVersion)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(WikiContribution::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(WikiContribution::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(WikiContribution::SourceId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiContribution::RawHash)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WikiContribution::AnnotationRevision)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(WikiContribution::NoteId).string().not_null())
                    .col(ColumnDef::new(WikiContribution::ClaimId).string().null())
                    .col(ColumnDef::new(WikiContribution::EvidenceId).string().null())
                    .col(ColumnDef::new(WikiContribution::CaseId).string().null())
                    .col(ColumnDef::new(WikiContribution::CommitId).string().null())
                    .col(
                        ColumnDef::new(WikiContribution::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
    }
}

#[derive(Iden)]
enum WikiVault {
    Table,
    Id,
    CanonicalPath,
    ConfigRevision,
    NextCompileAt,
    IsActive,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum WikiProjectBinding {
    Table,
    Id,
    VaultId,
    DbInstanceId,
    RootFolderId,
    ProjectNoteId,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum WikiSource {
    Table,
    Id,
    SourceGroupId,
    VaultId,
    SourceKind,
    SourceSeq,
    RunId,
    OriginalHash,
    RawPath,
    RawHash,
    ExtractorVersion,
    CoverageStatus,
    Eligibility,
    MaterialRole,
    PersonalRole,
    AnnotationRevision,
    ConversationId,
    FolderId,
    RootFolderId,
    AgentType,
    Model,
    Mode,
    CapturedAt,
    OccurredAt,
    Truncated,
    Redacted,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum WikiJob {
    Table,
    Id,
    VaultId,
    SourceId,
    Kind,
    Status,
    DedupeKey,
    InputManifest,
    ConfigVersion,
    ModelId,
    Protocol,
    Attempt,
    ErrorCode,
    ErrorMessage,
    OutputManifest,
    StartedAt,
    FinishedAt,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum WikiSourceSegment {
    Table,
    Id,
    SourceId,
    SegmentId,
    ContentHash,
    Locator,
    AnnotationRevision,
    CompileContractVersion,
    AnalysisConfigVersion,
    Stage,
    Artifact,
    Status,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum WikiCompileInput {
    Table,
    Id,
    SourceId,
    RawHash,
    AnnotationRevision,
    CompileContractVersion,
    CommittedJobId,
    CreatedAt,
}

#[derive(Iden)]
enum WikiContribution {
    Table,
    Id,
    SourceId,
    RawHash,
    AnnotationRevision,
    NoteId,
    ClaimId,
    EvidenceId,
    CaseId,
    CommitId,
    CreatedAt,
}
